const products = [
  {
    id: 1,
    title: 'Áo thun nam',
    price: 250000,
    description: 'Áo thun nam chất liệu cotton 100%',
    image: '/images/ao-thun-nam.jpg',
    category: 'Áo',
  },
  {
    id: 2,
    title: 'Quần jean nữ',
    price: 450000,
    description: 'Quần jean nữ form rộng cá tính',
    image: '/images/quan-jean-nu.jpg',
    category: 'Quần',
  },
  {
    id: 3,
    title: 'Giày thể thao',
    price: 650000,
    description: 'Giày thể thao phong cách trẻ trung',
    image: '/images/giay-the-thao.jpg',
    category: 'Giày',
  },
  {
    id: 4,
    title: 'Áo sơ mi nam',
    price: 320000,
    description: 'Áo sơ mi nam phong cách công sở',
    image: '/images/ao-so-mi-nam.jpg',
    category: 'Áo',
  },
  {
    id: 5,
    title: 'Quần short nữ',
    price: 280000,
    description: 'Quần short nữ thoải mái, năng động',
    image: '/images/quan-short-nu.jpg',
    category: 'Quần',
  },
  {
    id: 6,
    title: 'Giày lười nam',
    price: 580000,
    description: 'Giày lười nam da cao cấp',
    image: '/images/giay-luoi-nam.jpg',
    category: 'Giày',
  },
  {
    id: 7,
    title: 'Áo khoác nữ',
    price: 720000,
    description: 'Áo khoác nữ giữ ấm, thời trang',
    image: '/images/ao-khoac-nu.jpg',
    category: 'Áo',
  },
  {
    id: 8,
    title: 'Quần kaki nam',
    price: 520000,
    description: 'Quần kaki nam thoải mái, dễ phối đồ',
    image: '/images/quan-kaki-nam.jpg',
    category: 'Quần',
  },
  {
    id: 9,
    title: 'Giày cao gót nữ',
    price: 480000,
    description: 'Giày cao gót nữ thanh lịch, sang trọng',
    image: '/images/giay-cao-got-nu.jpg',
    category: 'Giày',
  },
];

export default products;
